# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/PROJECT/VIVADO/nhom12/nhom12.srcs/sources_1/bd/nhom12/ip/nhom12_axi_gpio_0_0/nhom12_axi_gpio_0_0.xci
# IP: The module: 'nhom12_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_gpio_0_0/nhom12_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'nhom12_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_gpio_0_0/nhom12_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'nhom12_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/PROJECT/VIVADO/nhom12/nhom12.srcs/sources_1/bd/nhom12/ip/nhom12_axi_gpio_0_0/nhom12_axi_gpio_0_0.xci
# IP: The module: 'nhom12_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_gpio_0_0/nhom12_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'nhom12_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_gpio_0_0/nhom12_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'nhom12_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
