# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/PROJECT/VIVADO/nhom12/nhom12.srcs/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/nhom12_axi_smc_0.xci
# IP: The module: 'nhom12_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/bd_8ec5.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_1/bd_8ec5_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_2/bd_8ec5_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_3/bd_8ec5_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_4/bd_8ec5_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_5/bd_8ec5_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_6/bd_8ec5_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_7/bd_8ec5_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_8/bd_8ec5_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_9/bd_8ec5_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_10/bd_8ec5_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_11/bd_8ec5_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_12/bd_8ec5_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_1/bd_8ec5_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_5/bd_8ec5_s00a2s_0_ooc.xdc

# XDC: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_6/bd_8ec5_sarn_0_ooc.xdc

# XDC: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_7/bd_8ec5_srn_0_ooc.xdc

# XDC: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_8/bd_8ec5_sawn_0_ooc.xdc

# XDC: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_9/bd_8ec5_swn_0_ooc.xdc

# XDC: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_10/bd_8ec5_sbn_0_ooc.xdc

# XDC: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_11/bd_8ec5_m00s2a_0_ooc.xdc

# XDC: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'nhom12_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'nhom12_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/PROJECT/VIVADO/nhom12/nhom12.srcs/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/nhom12_axi_smc_0.xci
# IP: The module: 'nhom12_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/bd_8ec5.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_1/bd_8ec5_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_2/bd_8ec5_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_3/bd_8ec5_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_4/bd_8ec5_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_5/bd_8ec5_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_6/bd_8ec5_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_7/bd_8ec5_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_8/bd_8ec5_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_9/bd_8ec5_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_10/bd_8ec5_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_11/bd_8ec5_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_12/bd_8ec5_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_1/bd_8ec5_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_5/bd_8ec5_s00a2s_0_ooc.xdc

# XDC: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_6/bd_8ec5_sarn_0_ooc.xdc

# XDC: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_7/bd_8ec5_srn_0_ooc.xdc

# XDC: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_8/bd_8ec5_sawn_0_ooc.xdc

# XDC: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_9/bd_8ec5_swn_0_ooc.xdc

# XDC: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_10/bd_8ec5_sbn_0_ooc.xdc

# XDC: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/bd_0/ip/ip_11/bd_8ec5_m00s2a_0_ooc.xdc

# XDC: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'nhom12_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/ip/nhom12_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'nhom12_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
