# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/nhom12/nhom12.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nhom12 || ORIG_REF_NAME==nhom12} -quiet] -quiet

# IP: bd/nhom12/ip/nhom12_processing_system7_0_0/nhom12_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nhom12_processing_system7_0_0 || ORIG_REF_NAME==nhom12_processing_system7_0_0} -quiet] -quiet

# IP: bd/nhom12/ip/nhom12_axi_gpio_0_0/nhom12_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nhom12_axi_gpio_0_0 || ORIG_REF_NAME==nhom12_axi_gpio_0_0} -quiet] -quiet

# IP: bd/nhom12/ip/nhom12_axi_smc_0/nhom12_axi_smc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nhom12_axi_smc_0 || ORIG_REF_NAME==nhom12_axi_smc_0} -quiet] -quiet

# IP: bd/nhom12/ip/nhom12_rst_ps7_0_50M_0/nhom12_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==nhom12_rst_ps7_0_50M_0 || ORIG_REF_NAME==nhom12_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: e:/PROJECT/VIVADO/nhom12/nhom12.gen/sources_1/bd/nhom12/nhom12_ooc.xdc
